tfm/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

import views
from tfm import settings

urlpatterns = patterns('',
                       url(r'^$', views.index),
                       url(r'^registration/', views.registration),
                       url(r'^login/', views.index),
                       url(r'^logout/', views.user_logout),
                       url(r'^crossdomain', views.crossdomain),
                       url(r'^accounts/login/$', views.index),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/', include('allauth.urls')),
                       url(r'^notifications/', views.notifications),
                       url(r'^patients/$', views.list_patients),
                       url(r'^patients/patient', views.patient),
                       url(r'^patients/create', views.create_patient),
                       url(r'^patients/settings', views.patient_settings),
                       url(r'^patients/validateCode', views.validate_patient_code),
                       url(r'^patients/testResult', views.test_result),
                       url(r'^sendTestResult', views.send_test_result),
                       )


# Media URLs
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tfm/models.py
from django.contrib.auth.models import User
from django.db import models

class Doctor(models.Model):
    specialization = models.CharField(max_length=100)


class PatientSettings(models.Model):
    # 0 means the test is locked for the patient, -1 means no minimum diary tests.
    diary_straight_line = models.IntegerField(default=-1)
    diary_simon_says_hand = models.IntegerField(default=-1)
    diary_simon_says_tool = models.IntegerField(default=-1)

    simon_says_hand_max_hooks = models.IntegerField(default=5)
    simon_says_tool_max_hooks = models.IntegerField(default=5)


class Patient(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICES = (
        (True, 'Male'),
        (False, 'Female'),
    )

    first_name = models.CharField(max_length=100, null=False, default='')
    last_name = models.CharField(max_length=200, null=False, default='')
    history = models.TextField()
    sex = models.BooleanField(max_length=1, choices=SEX_CHOICES)
    doctor = models.ForeignKey(User)
    birth_date = models.DateField()
    photo = models.ImageField(upload_to='photos', blank=True, default='photos/default.png')
    settings = models.ForeignKey(PatientSettings)

class TestResult(models.Model):
    SIMON_SAYS = "SS"
    STRAIGHT_LINE = "SL"
    SIMON_SAYS_TOOL = "ST"
    TEST_CHOICES = (
        (SIMON_SAYS, 'Simon says'),
        (STRAIGHT_LINE, "Straight line"),
        (SIMON_SAYS_TOOL, "Simon says with a tool")
    )
    test_type = models.CharField(max_length=2, choices=TEST_CHOICES)
    date = models.DateTimeField(auto_now_add=True)
    patient = models.ForeignKey(Patient)
    result = models.TextField()
    is_new = models.BooleanField(default=True)

tfm/forms.py
from django.contrib.auth import authenticate
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from django import forms
from models import Doctor, Patient, PatientSettings
from django.contrib.auth.models import User


class UserRegistrationForm(ModelForm):
    password2 = forms.CharField(label=_("Confirm password"), widget=forms.PasswordInput)

    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password')

        widgets = {
            'password': forms.PasswordInput(),
            'username': forms.EmailInput(),
        }
        labels = {
            'username': 'Email',
        }
        error_messages = {
            'username': {
                'unique': _("The email already exists."),
            },
        }
        help_texts = {
            'username': "",
        }

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password and password2 and password != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(), label='Password', max_length=50)

    def clean(self):
        username = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Incorrect user or password")
        return self.cleaned_data

    def login(self, request):
        username = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        return user


class CreatePatientForm(ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        widgets = {
            'history': forms.Textarea(attrs={'class': 'materialize-textarea', })
        }
        # We exclude the sex because MaterializeCss has some problems rendering it.
        exclude = ('doctor', 'sex', 'birth_date', 'settings')

class PatientSettingsForm(ModelForm):
    class Meta:
        model = PatientSettings
        fields = '__all__'

tfm/views.py
from random import Random
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, timedelta, date
from forms import UserRegistrationForm, LoginForm, CreatePatientForm, PatientSettingsForm
from tfm.models import Patient, TestResult, PatientSettings
import json

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            # Hash the password.
            print form.cleaned_data
            newUser = form.instance
            newUser.password = make_password(newUser.password)
            newUser.email = newUser.username
            newUser.save()
            return HttpResponseRedirect('/')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration.html', {'form': form})


def index(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.login(request)
            if user:
                login(request, user)
                return HttpResponseRedirect('/notifications')
            else:
                print"no"
    else:
        form = LoginForm()
    return render(request, 'index.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required
def create_patient(request):
    attrs = {}
    if request.method == 'POST':
        form = CreatePatientForm(request.POST, request.FILES)
        if form.is_valid():

            if request.POST.get('update') is not None:
                # Editing
                previous_patient = Patient.objects.filter(id=request.POST['update']).first()
                previous_patient.first_name = request.POST['first_name']
                previous_patient.last_name = request.POST['last_name']
                previous_patient.history = request.POST['history']

                if request.POST['sex'] == 'M':
                    previous_patient.sex = True
                else:
                    previous_patient.sex = False

                date_string = request.POST['birth_date']
                try:
                    day = int(date_string[0:2])
                    month = int(date_string[3:5])
                    year = int(date_string[6:10])
                    birth_date = date(year, month, day)
                    previous_patient.birth_date = birth_date
                except:
                    # Date didn't change.
                    previous_patient.birth_date = previous_patient.birth_date

                if request.FILES.get('photo') is not None:
                    # Change the photo
                    previous_patient.photo = request.FILES.get('photo')

                previous_patient.save()
            else:
                patient = form.instance
                # Since we excluded the sex in the form we need to get in from request.POST.
                if request.POST['sex'] == 'M':
                    patient.sex = True
                else:
                    patient.sex = False
                # The patient's doctor is the user
                patient.doctor = request.user
                # Create default settings
                settings = PatientSettings()
                settings.save()
                patient.settings = settings
                # Create a date from the form info
                date_string = request.POST['birth_date']
                print date_string
                day = int(date_string[0:2])
                month = int(date_string[3:5])
                year = int(date_string[6:10])
                birth_date = date(year, month, day)
                patient.birth_date = birth_date

                patient.save()
            return HttpResponseRedirect('/patients')
    else:
        form = CreatePatientForm()
        if request.GET.get('id') is not None:
            # Edit patient.
            patient = Patient.objects.filter(id=request.GET['id']).first()
            attrs['patient'] = patient
            # Prefill the text fields.
            form.fields['first_name'].initial = patient.first_name
            form.fields['last_name'].initial = patient.last_name
            form.fields['history'].initial = patient.history
    attrs['form'] = form
    return render(request, 'create_patient.html', attrs)


@login_required
def patient_settings(request):
    # Get patient
    patient = Patient.objects.filter(id=request.GET['id']).first()
    if request.method == 'POST':
        # Get sent data and save the settings.
        form = PatientSettingsForm(request.POST)
        if form.is_valid():
            settings = form.instance
            print settings.diary_straight_line
            previous_settings = patient.settings
            settings.save()
            patient.settings = settings
            patient.save()
            previous_settings.delete()

    render_form = PatientSettingsForm()

    # Prefill the fields
    settings = patient.settings
    render_form.fields['diary_straight_line'].initial = settings.diary_straight_line
    render_form.fields['diary_simon_says_hand'].initial = settings.diary_simon_says_hand
    render_form.fields['diary_simon_says_tool'].initial = settings.diary_simon_says_tool
    render_form.fields['simon_says_hand_max_hooks'].initial = settings.simon_says_hand_max_hooks
    render_form.fields['simon_says_tool_max_hooks'].initial = settings.simon_says_tool_max_hooks

    return render(request, 'patient_settings.html', {'patient': patient,
                                                     'form': render_form})

@login_required
def list_patients(request):
    if request.method == 'POST':
        # The doctor deleted a patient
        patient = Patient.objects.filter(id=request.POST['patient_id']).first()
        patient.delete()

    doctor_patients = Patient.objects.filter(doctor=request.user).order_by('last_name')

    for patient in doctor_patients:
        patient.code = str(patient.id).zfill(6)

    return render(request, 'patients.html', {'patients': doctor_patients})


@login_required
def notifications(request):
    # Get all unread notifications.
    unread_notifications = TestResult.objects.filter(is_new=True)

    # Filter by doctor.
    filtered_notifications = []
    for notification in unread_notifications:
        if notification.patient.doctor == request.user:
            filtered_notifications.append(notification)

    return render(request, 'notifications.html', {'notifications': filtered_notifications})


def crossdomain(request):
    return HttpResponse(open('crossdomain.xml').read())


def validate_patient_code(request):
    # Take off the zeros to the left.
    code = int(request.GET['code'])
    patient = Patient.objects.filter(id=code)
    response = {}
    if patient:
        response['first_name'] = patient[0].first_name
        response['last_name'] = patient[0].last_name
        response['ok'] = True
        response['diary_straight_line'] = patient[0].settings.diary_straight_line
        response['diary_simon_says_hand'] = patient[0].settings.diary_simon_says_hand
        response['diary_simon_says_tool'] = patient[0].settings.diary_simon_says_tool
        response['simon_says_hand_max_hooks'] = patient[0].settings.simon_says_hand_max_hooks
        response['simon_says_tool_max_hooks'] = patient[0].settings.simon_says_tool_max_hooks
    else:
        response['ok'] = False
    print response
    return HttpResponse(json.dumps(response))


@login_required
def patient(request):
    # Get the patient
    patient_id = request.GET['id']
    patient_object = Patient.objects.filter(id=patient_id).first()

    if request.method == 'POST':
        # The doctor changed user history
        new_history = request.POST['history']
        patient_object.description = new_history
        patient_object.save()

    # Get test results
    test_results = TestResult.objects.filter(patient=patient_object).order_by('-date')

    return render(request, 'patient.html', {'patient': patient_object,
                                            'test_results': test_results,
                                            })


@login_required
def test_result(request):
    test_id = request.GET['id']
    test = TestResult.objects.filter(id=test_id).first()

    # If the doctor acceded it then it isn't new.
    if test.is_new:
        test.is_new = False
        test.save()


    if (test.test_type == 'SS'):

        # Since the fingers and the times aren't sorted it's necessary to do it this way.
        coordinates = ['x', 'y', 'z']
        thumb_coords = [[], [], []]
        index_coords = [[], [], []]
        middle_coords = [[], [], []]
        ring_coords = [[], [], []]
        pinky_coords = [[], [], []]

        test_json = json.loads(test.result)

        for i in range(0, test_json['times'].keys().__len__()):
            # In each iteration we add either a x, y or z coord.
            for j in range(0, coordinates.__len__()):
                # Add a "[<time>, <position in axis>]," string to each array.
                coordinate = coordinates[j]
                thumb_coords[j].append(
                    '[' + test_json['times'][str(i)] + ', ' + str(float(test_json['thumb'][coordinate][str(i)]) / 10) + ']')
                index_coords[j].append(
                    '[' + test_json['times'][str(i)] + ', ' + str(float(test_json['index'][coordinate][str(i)]) / 10) + ']')
                middle_coords[j].append(
                    '[' + test_json['times'][str(i)] + ', ' + str(
                        float(test_json['middle'][coordinate][str(i)]) / 10) + ']')
                ring_coords[j].append(

tfm/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo right">Hand Control Platform</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="/registration/">Registration</a></li>
                <li><a href="/login/">Login</a></li>
            </ul>
        </div>
    </nav>
<div class="container">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

tfm/templates/base_logged_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
    <title>{% block title %}{% endblock title %}</title>

    <script>
        $(".dropdown-button").dropdown();
    </script>

</head>
<body>
{#Patients dropdown#}
<ul id="patientsDropdown" class="dropdown-content">
    <li><a href="/notifications">Notifications</a></li>
    <li><a href="/patients">List</a></li>
    <li><a href="/patients/create">Create</a></li>
</ul>
<nav>
    <div class="nav-wrapper">
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li>
                <a href="#!" class="dropdown-button" data-activates="patientsDropdown">
                    Patients
                    <i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>
        </ul>
        {% block breadcrumbs %}{% endblock %}
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/logout">Log out</a></li>
            <a href="#" class="brand-logo center">Hand Control Platform</a>
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock content %}
</div>
</body>
</html>

tfm/templates/create_patient.html
{% extends "base_logged_in.html" %}



{% block title %}Create Patient{% endblock title %}

{% block content %}
    <script>
        $(document).ready(function () {
            $('.datepicker').pickadate({
                selectMonths: true, // Creates a dropdown to control month
                selectYears: 180, // Creates a dropdown of 15 years to control year
                format: 'dd/mm/yyyy'
            });
        });
    </script>
    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if patient %}
            <input type=hidden name='update' value={{ patient.id }}>
        {% endif %}
        {{ form }}
        <br>
        <label>Sex:</label>
        {% if patient.sex != False %}
            <p>
                <input name="sex" type="radio" id="male" value="M" required checked>
                <label for="male">Male</label>
            </p>
            <p>
                <input name="sex" type="radio" id="female" value="F" required>
                <label for="female">Female</label>
            </p>
        {% else %}
            <p>
                <input name="sex" type="radio" id="male" value="M" required>
                <label for="male">Male</label>
            </p>
            <p>
                <input name="sex" type="radio" id="female" value="F" required checked>
                <label for="female">Female</label>
            </p>
        {% endif %}

        <label>Birth date:</label>
        <input type="date" class="datepicker" name="birth_date" id="date" required placeholder="Click to select date" value="{{ patient.birth_date }}">
        <button type="button" class="btn waves-effect waves-light" onclick="submitform()">
            {% if patient %}
                Save
            {% else %}
                Create
            {% endif %}
        </button>
        <input id="submit_handle" type="submit" style="display: none">
        <script>
            function submitform() {
                if ($('#date').val() == ""){
                    alert("Please enter a date");
                }
                else
                    $('#submit_handle').click();
            }
        </script>
    </form>
{% endblock content %}

tfm/templates/index.html
{% extends "base.html" %}

{% block title %}Hand Control Platform{% endblock title %}

{% block content %}
    <h1>Welcome to the Hand Control Platform.</h1>
    <h3>Please log in or register</h3>

    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type=submit class="btn waves-effect waves-light">Log in</button>
    </form>
{% endblock content %}

tfm/templates/notifications.html
{% extends "base_logged_in.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h3>Welcome, {{ user.first_name }} {{ user.last_name }}</h3>

    <h5>Unread notifications:</h5>

    <ul class="collection">
        {% for notification in notifications %}
            <a href="/patients/testResult?id={{ notification.id }}" class="collection-item">
                <li class="collection-item">
                    <span class="title"><b>Type:</b> {{ notification.get_test_type_display}}</span>
                    <p><b>Patient: </b>{{ notification.patient.last_name }}, {{ notification.patient.first_name }} </p>
                    <p><b>Date: </b>{{ notification.date }}</p>
                </li>
            </a>
        {% empty %}
            <li>No unread notifications.</li>
        {% endfor %}
    </ul>
{% endblock content %}

tfm/templates/patient.html
{% extends "base_logged_in.html" %}
{% block title %}{{ patient.last_name }}, {{ patient.first_name }}{% endblock title %}
{% block breadcrumbs %}
<a class='breadcrumb'>{{ patient.last_name }}, {{ patient.first_name }}</a>
{% endblock %}
{% block content %}
    <h4>{{ patient.last_name }}, {{ patient.first_name }}</h4>

    <img src="{{ patient.photo.url }}" width="200px">
    <form action="#" method="POST">
        {% csrf_token %}
        <h5>History</h5>
        <br>

        <div class=row>
            <div class="input-field">
                <textarea id="history" name="history" class="materialize-textarea"
                          placeholder="">{{ patient.history }}</textarea>
                <label for=history class="active">Click to edit.</label>
            </div>
            <button type=submit class="btn waves-effect waves-light">Save</button>
        </div>
    </form>
    <h4>Tests</h4>
    <ul class="collection">
        {% for test_result in test_results %}
            <a href="testResult?id={{ test_result.id }}" class="collection-item">
                <li class="collection-item">
                    <span class="title"><b>Type:</b> {{ test_result.get_test_type_display }}</span>

                    <p><b>Date: </b>{{ test_result.date }}</p>
                </li>
            </a>
        {% empty %}
            <li>This patient hasn't realized any tests.</li>
        {% endfor %}
    </ul>

    <div class=row>
        <div class="input-field">
            <a class="btn waves-effect waves-light" href="/patients/create?id={{ patient.id }}">Edit Patient</a>
            <a class="btn waves-effect waves-light" href="/patients/settings?id={{ patient.id }}">Edit Settings</a>
        </div>
    </div>
    <form action="/patients/" method="POST" onsubmit="return confirm('Do you really want to delete this patient?');">
        {% csrf_token %}
        <div class=row>
            <div class="input-field">
                <input type="hidden" value="{{ patient.id }}" name="patient_id">
                <button type=submit class="btn waves-effect waves-light red">Delete patient</button>
            </div>
        </div>
    </form>

{% endblock content %}

tfm/templates/patient_settings.html
{% extends "base_logged_in.html" %}
{% block title %}{{ patient.last_name }}, {{ patient.first_name }}{% endblock title %}
{% block breadcrumbs %}
    <a href='/patients/patient?id={{ patient.id }}' class='breadcrumb'>{{ patient.last_name }}, {{ patient.first_name }}</a>
    <a class='breadcrumb'>Tests settings</a>
{% endblock %}
{% block content %}
    <h3>{{ patient.first_name }} {{ patient.last_name }}'s test settings</h3>
    <h5>Instructions:</h5>
    <h6>For diary settings, enter -1 if you don't want to assign the patient a minimum number of diary test.
        Enter 0 if you don't want the patient to perform the test.</h6>
    <form action="#" method='POST'>
        {% csrf_token %}
        {{ form }}
        <button type=submit class="btn waves-effect waves-light">Save</button>
    </form>

{% endblock %}

tfm/templates/patients.html
{% extends "base_logged_in.html" %}

{% block title %}Patients{% endblock title %}

{% block content %}
    <ul class="collection">
        {% for patient in patients %}
            <a href="patient?id={{ patient.id }}" class="collection-item">
                <li class="collection-item avatar">
                    <img src="{{ MEDIA_URL }}{{ patient.photo.url }}" alt="" class="circle">
                    <span class="title">{{ patient.last_name }}, {{ patient.first_name }}</span>
                    <p>Code: {{ patient.code }}</p>
                </li>
            </a>
        {% empty %}
            <li>You have no patients yet.</li>
        {% endfor %}
    </ul>


{% endblock content %}

tfm/templates/registration.html
{% extends "base.html" %}

{% block title %}Registration{% endblock title %}

{% block content %}
    <form action="#" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register" class="btn waves-effect waves-light"/>
    </form>
{% endblock content %}